<?php
/*
 * @author: petereussen
 * @package: pressmarket
 */

namespace HarperJones\Wordpress\Http;


use Symfony\Component\HttpFoundation\Request;

class WordpressRequest extends Request
{
	public function initialize( array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null )
	{
		parent::initialize( $query, $request, $attributes, $cookies, $files, $server, $content ); // TODO: Change the autogenerated stub
		$this->getUrlParameters();
	}

	private function getUrlParameters()
	{
		$uri    = $this->getRequestUri();
		$perma  = wp_make_link_relative(get_permalink());
		$params = rtrim(str_replace($perma,'',$uri),'/');
		$sets   = explode("/",$params);

		while ( $sets ) {
			$key = array_shift($sets);
			$val = array_shift($sets);

			if ( $key && $val ) {
				$this->query->set($key,$val);
			}
		}
	}
}